#!/bin/bash
#
# Generated by dcnode
#
bash -c "echo -n 'start at ' && date" >> /dockerdata/start_history.log
source ~/.bash_profile
ulimit -c unlimited
cd /usr/local/app/taf/app_log
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/app/taf/cham.TafTemplateServer/bin/:/usr/local/app/taf/lib
nohup java -Dis.selftest.env=true -Dconfig=/usr/local/app/taf/cham.TafTemplateServer/conf/taf.config.conf -Dcom.sun.management.jmxremote.port=jmxPort -javaagent:/usr/local/app/taf/cham.TafTemplateServer/bin/apps/ROOT/WEB-INF/lib/jacocoagent.jar=includes=com.tencent.cham.taftemplate.*,output=tcpserver,address=127.0.0.1,port=jacocoPort -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xms2000m -Xmx2000m -Xmn1000m -Xss1000k -XX:PermSize=128M -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=60 -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=0 -verbosegc -XX:+PrintGCDetails -XX:ErrorFile=/usr/local/app/taf/app_log//cham/TafTemplateServer/jvm_error.log -cp /usr/local/app/taf/cham.TafTemplateServer/bin/classes:/usr/local/app/taf/cham.TafTemplateServer/bin//conf:/usr/local/app/taf/cham.TafTemplateServer/bin//lib/* com.qq.cloud.taf.server.startup.Main  2>&1 | tee /usr/local/app/start.log >> /dockerdata/start_history.log 2>&1 &
